services:
  postgres:
    image: postgres:15
    container_name: keycloak_db
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpass
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak"]
      interval: 30s
      timeout: 10s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloakpass
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      keycloak:
        condition: service_started
    restart: unless-stopped

  
  lgm8-auth-service:
    build:
      context: ../
      dockerfile: microservices/lgm8-auth-service/dockerfile
    container_name: lgm8-auth-service
    environment:
      - GIN_MODE=debug
      - GIN_TRUSTED_PROXIES=nginx,keycloak
    ports:
      - "8081:8081"
    depends_on:
      keycloak:
        condition: service_started
    # restart: unless-stopped
